# Makefile for Markdown2HTML
#

COMPONENT  = Markdown2HTML
TYPE       = aif
INCLUDES   = <Lib$Dir>.MarkdownMD4C.
LIBS       = ${CLIB} ${GETOPTLIB} <Lib$Dir>.MarkdownMD4C.o.libMarkdownMD4C
OBJS       = o.cmdline \
             o.entity \
             o.md2html \
             o.render_html \

include LibraryCommand


#---------------------------------------------------------------------------
# Dynamic dependencies:
